from pyrogram import Client
alf = open(".Number.csv","r").read()
alf1 = alf.split()

app0 = Client("My_Account924829",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[0])+".txt", "r").read())
app1 = Client("My_Account501205",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[1])+".txt", "r").read())
app2 = Client("My_Account731873",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[2])+".txt", "r").read())
app3 = Client("My_Account484083",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[3])+".txt", "r").read())
app4 = Client("My_Account918273",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[4])+".txt", "r").read())
app5 = Client("My_Account968311",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[5])+".txt", "r").read())
app6 = Client("My_Account463078",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[6])+".txt", "r").read())
app7 = Client("My_Account675264",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[7])+".txt", "r").read())
app8 = Client("My_Account686872",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[8])+".txt", "r").read())
app9 = Client("My_Account875282",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[9])+".txt", "r").read())
app10 = Client("My_Account22742",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[10])+".txt", "r").read())
app11 = Client("My_Account613126",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[11])+".txt", "r").read())
app12 = Client("My_Account895002",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[12])+".txt", "r").read())
app13 = Client("My_Account557775",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[13])+".txt", "r").read())
app14 = Client("My_Account206903",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[14])+".txt", "r").read())
app15 = Client("My_Account777191",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[15])+".txt", "r").read())
app16 = Client("My_Account835457",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[16])+".txt", "r").read())
app17 = Client("My_Account621271",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[17])+".txt", "r").read())
app18 = Client("My_Account118015",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[18])+".txt", "r").read())
app19 = Client("My_Account666792",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[19])+".txt", "r").read())
app20 = Client("My_Account185210",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[20])+".txt", "r").read())
app21 = Client("My_Account567625",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[21])+".txt", "r").read())
app22 = Client("My_Account905800",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[22])+".txt", "r").read())
app23 = Client("My_Account983546",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[23])+".txt", "r").read())
app24 = Client("My_Account226756",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[24])+".txt", "r").read())
app25 = Client("My_Account578097",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[25])+".txt", "r").read())
app26 = Client("My_Account730642",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[26])+".txt", "r").read())
app27 = Client("My_Account452975",session_string=open("/storage/emulated/0/Android/media/com.google.h/.Number_H/"+str(alf1[27])+".txt", "r").read())

apps = [app0 ,app1 ,app2 ,app3 ,app4 ,app5 ,app6 ,app7 ,app8 ,app9 ,app10 ,app11 ,app12 ,app13 ,app14 ,app15 ,app16 ,app17 ,app18 ,app19 ,app20 ,app21 ,app22 ,app23 ,app24 ,app25 ,app26 ,app27]